server:
  port: 8088
spring:
  application:
    name: sneaker-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: eshop
    password: eshop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update